export const dummyItems = [
    {   id: 0,
        path: 'Images/Hoodie/', 
        price: 49.50, 
        pname: 'Hoodie Detitalismo',
        pdesc: 'This 100% cotton hoodie was made by extrmely advanced robots created by DETI students, the best engineers in the world. This hoodie is made to last and to give you confort everyday.',
        category: 'Clothes',
        stock: 2},
    
    {   id: 1,
        path: 'Images/Cup/', 
        price: 5.50, 
        pname: 'Java Thermal Cup',
        pdesc: 'This thermal cup was made with recycled coffee beans from DETIs machine. It can withstand both high and freezing tempratures, while saving your hands from potential burns. However, Be Careful With Your Tongue.',
        category: 'Home',
        stock: 10},

    {   id: 2,
        path: 'Images/HeadPhones/', 
        price: 65.00, 
        pname: 'DETI HeadPhones',
        pdesc: 'For all the hours of hard work our enginners endure we created this amazing wireless headphones. For music, gaming or hours of reunions they give ou the best accoustic inside while keeping every other noise outside.',
        category: 'Accessories',
        stock: 10},

    {   id: 3,
        path: 'Images/MousePad/', 
        price: 10.65, 
        pname: 'Marble MousePad',
        pdesc: 'Do you want to increase your poductivity while keeping your setup super clean? This mousepad alows exactly that giving you a confortable and durable surface for everyday use.',
        category: 'Home',
        stock: 0},

    {   id: 4,
        path: 'Images/Cap/', 
        price: 10, 
        pname: 'Java Protected Cap',
        pdesc: 'You may not leave your chair a lot but if you do, you must be protected. This stylish cap can protect and your eyes from every bit os excess light, also blocking UVA and UVB.',
        category: 'Clothes',
        stock: 10},
]
